version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: paas_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "npm install && npm start"

  interface:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./interface-client:/app
    ports:
      - "5173:5173"
    depends_on:
      - api
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  # --- LES NOUVEAUX COMPOSANTS DU CONTROL PLANE ---

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  control-plane:
    image: node:20-alpine
    working_dir: /app
    volumes:
      # Assure-toi que ton dossier s'appelle bien "control-plane" à la racine
      - ./control-plane:/app 
    ports:
      - "4000:4000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    command: sh -c "npm install && node index.js"

volumes:
  db-data: