Vagrant.configure("2") do |config|

  # La boucle qui va compter de 1 à 10
  (1..3).each do |i|
    
    # "w" représente la machine en cours de création dans la boucle
    config.vm.define "worker-#{i}" do |w|
      
      w.vm.box = "generic/debian12"
      
      # Le nom interne devient worker-1, worker-2...
      w.vm.hostname = "worker-#{i}"
      
      # L'IP devient dynamique : 192.168.56.11, 192.168.56.12...
      w.vm.network "private_network", ip: "192.168.56.#{10 + i}"
      
      # Le port hôte devient dynamique : 12351, 12352... pour éviter les conflits
      w.vm.network "forwarded_port", guest: 80, host: 12350 + i, host_ip: "127.0.0.1"
      
      # Le dossier partagé
      w.vm.synced_folder "./vagrant_data", "/vagrant_data"
      
      w.vm.provider "virtualbox" do |vb|
        # Le nom affiché dans VirtualBox devient worker-1, worker-2...
        vb.name = "worker-#{i}"
        vb.gui = false
        vb.memory = 1024
        vb.cpus = 2
      end
      
    end
  end

  # Provisioning Ansible global (s'appliquera à toutes les machines)
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

end