# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessible to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.define "worker-1" do |w1|
  #   # Display the VirtualBox GUI when booting the machine
      w1.vm.network "forwarded_port", guest: 80, host: 12355, host_ip: "127.0.0.1"
      w1.vm.box = "generic/debian12"
      w1.vm.hostname = "worker-1"
      w1.vm.network "private_network", ip:"192.168.56.11" 
      w1.vm.synced_folder "./vagrant_data", "/vagrant_data"
  #
  #  
      # Configuration spécifique à VirtualBox
      w1.vm.provider "virtualbox" do |v|
        v.gui = false
        v.memory = "1024"
        v.cpus = 2
        v.name = "worker-1"
      end

      # Configuration ansible pour le worker-1
      config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
      end
   end
  #

  config.vm.define "worker-2" do |w2|
  #   # Display the VirtualBox GUI when booting the machine
      w2.vm.network "forwarded_port", guest: 80, host: 12354, host_ip: "127.0.0.1"
      w2.vm.box = "generic/debian12"
      w2.vm.hostname = "worker-2"
      w2.vm.network "private_network", ip:"192.168.56.10" 
      w2.vm.synced_folder "./vagrant_data", "/vagrant_data"
  #
  #   # Customize the amount of memory on the VM:
      # Configuration spécifique à VirtualBox
      w2.vm.provider "virtualbox" do |v|
        v.gui = false
        v.memory = "1024"
        v.cpus = 2
        v.name = "worker-2"
      end

      config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
      end
   end
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

end
