name: PaaS CI Validation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code source
        uses: actions/checkout@v4

      - name: Configuration de l'environnement Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 1. Installation et Tests de l'API
      - name: Installation et Tests (API)
        run: |
          npm install
          npm test (décommente quand tu auras ajouté tes scripts de test)
        working-directory: ./api

      # 2. Installation et Tests du Control Plane
      - name: Installation et Tests (Control Plane)
        run: |
          npm install
          npm test
        working-directory: ./control-plane

      # 3. Installation et Build du Frontend (Interface Client)
      - name: Installation et Build (Interface Client)
        run: |
          npm install
          npm run build
        working-directory: ./interface-client

      # 4. Vérification syntaxique du playbook Ansible
      - name: Validation Playbook Ansible
        run: |
          sudo apt-get update && sudo apt-get install -y ansible
          ansible-playbook --syntax-check worker-template/playbook.yml